# Generated by Django 3.2.9 on 2022-01-20 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import exiffield.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('photo', django_resized.forms.ResizedImageField(crop=None, default='author pic', force_format='JPEG', keep_meta=True, quality=75, size=[500, 400], upload_to='authors')),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Catagory',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('edited', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], default='unpublished', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('comments_option', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='myblog.author')),
                ('tags', taggit.managers.TaggableManager(help_text='Use comma to separate', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Add Tags')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('feature_image', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, editable=False, max_length=150)),
                ('lens', models.TextField(default='Lens Data', editable=False, max_length=100)),
                ('caption', models.CharField(default='Caption info', editable=False, max_length=1000)),
                ('file_size', models.CharField(default='File_size', editable=False, max_length=20)),
                ('info', models.TextField(blank=True, default='**info empty**', help_text='editable caption info no reversable')),
                ('exif', exiffield.fields.ExifField(default={}, editable=False)),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myblog.catagory')),
                ('posts', models.ManyToManyField(blank=True, related_name='pictures', to='myblog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
