# Generated by Django 3.2.9 on 2022-01-20 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
