# Generated by Django 3.2.9 on 2022-01-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_alter_post_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gallery',
            field=models.ForeignKey(default='Gallery', on_delete=django.db.models.deletion.CASCADE, to='myblog.gallery'),
        ),
    ]
