# Generated by Django 3.2.9 on 2022-01-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_alter_post_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='tile',
            new_name='title',
        ),
    ]
