# Generated by Django 3.2.9 on 2022-01-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_rename_tile_gallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
