# Generated by Django 3.2.9 on 2022-01-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_delete_gallery'),
        ('myblog', '0008_gallery_title'),
    ]

    operations = [
    ]
