# Generated by Django 3.2.9 on 2022-01-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='albums',
            field=models.ManyToManyField(blank=True, to='myblog.Album'),
        ),
    ]
