# Generated by Django 4.0 on 2022-01-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
