# Generated by Django 4.0 on 2022-01-03 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_alter_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
    ]
