# Generated by Django 4.0 on 2022-01-04 13:37

from django.db import migrations, models
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0013_remove_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
