# Generated by Django 4.0 on 2022-01-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0014_image_exif_alter_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lens',
            field=models.CharField(default='Lens Data', editable=False, max_length=100),
        ),
    ]
