# Generated by Django 4.0 on 2022-01-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_image_caption_alter_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='lens',
            field=models.TextField(default='Lens Data', editable=False, max_length=100),
        ),
    ]
