# Generated by Django 4.0 on 2022-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0018_alter_image_lens'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.CharField(default='File_size', editable=False, max_length=20),
        ),
    ]
