# Generated by Django 4.0 on 2022-01-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_image_file_size'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
    ]
