# Generated by Django 4.0 on 2022-01-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0020_rename_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='posts',
            field=models.ManyToManyField(to='myblog.Post'),
        ),
    ]
