# Generated by Django 4.0 on 2022-01-05 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0021_photo_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='posts',
            field=models.ManyToManyField(related_name='pictures', to='myblog.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='myblog.author'),
        ),
    ]
