# Generated by Django 4.0 on 2022-01-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_alter_photo_posts_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='posts',
            field=models.ManyToManyField(to='myblog.Post'),
        ),
    ]
