# Generated by Django 4.0 on 2022-01-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0024_alter_photo_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='posts',
        ),
    ]
