# Generated by Django 4.0 on 2022-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0025_remove_photo_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(related_name='blog_posts', to='myblog.Photo'),
        ),
    ]
