# Generated by Django 4.0 on 2022-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0027_remove_post_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='posts',
            field=models.ManyToManyField(related_name='pictures', to='myblog.Post'),
        ),
    ]
