# Generated by Django 4.0 on 2022-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0028_photo_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(default='Caption info', editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='photo',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='pictures', to='myblog.Post'),
        ),
    ]
