# Generated by Django 4.0 on 2022-01-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0029_alter_photo_caption_alter_photo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myblog.photo')),
            ],
        ),
    ]
