# Generated by Django 4.0 on 2022-01-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0030_iptc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iptc',
            options={'verbose_name_plural': 'IPTC'},
        ),
        migrations.RemoveField(
            model_name='iptc',
            name='data',
        ),
        migrations.AddField(
            model_name='post',
            name='feature_image',
            field=models.BooleanField(default=False),
        ),
    ]
