# Generated by Django 4.0 on 2022-01-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0032_remove_post_feature_image_photo_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='info',
            field=models.CharField(default='info', max_length=500),
        ),
    ]
