# Generated by Django 4.0 on 2022-01-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0033_photo_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='info',
            field=models.TextField(default='info'),
        ),
    ]
