# Generated by Django 4.0 on 2022-01-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0034_alter_photo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptc',
            name='caption',
            field=models.TextField(default='caption'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='info',
            field=models.TextField(default='**info empty**'),
        ),
    ]
