# Generated by Django 4.0 on 2022-01-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0035_iptc_caption_alter_photo_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptc',
            name='caption',
        ),
        migrations.AddField(
            model_name='iptc',
            name='data',
            field=models.CharField(default='caption', max_length=500),
        ),
    ]
