# Generated by Django 4.0 on 2022-01-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0036_remove_iptc_caption_iptc_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iptc',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.photo'),
        ),
    ]
