# Generated by Django 4.0 on 2022-01-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0038_catagory_rename_picture_iptc_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myblog.catagory'),
        ),
    ]
